title: Jim Law
email: jimlaw@byu.edu
description: >
  Information about my research and teaching
baseurl: ""
url: ""
twitter_username: jimlaloi
github_username:  jimlaloi

theme: minima
plugins:
  - jekyll-feed
